import AppKit
import Combine
import SwiftUI

/// The Mac's half of the shared clipboard.
///
/// AppKit has no "pasteboard changed" notification, so noticing a copy means
/// watching `changeCount` on a timer — what every clipboard tool on the platform
/// does. The poll is cheap: `changeCount` is an integer read, and the pasteboard
/// is only actually opened when that integer moves.
@MainActor
final class ClipboardWatcher: ObservableObject {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    /// The last text that crossed the link in either direction. Without it the
    /// two devices would trade the same copy back and forth forever: writing
    /// what the phone sent moves `changeCount`, which reads as a fresh copy.
    private var lastText: String?
    private var timer: Timer?
    private var cancellables = Set<AnyCancellable>()
    private weak var pairing: PairingManager?

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func attach(to pairing: PairingManager) {
        // The window can be rebuilt (closed and reopened from the menu bar),
        // and a second timer would double every send.
        guard self.pairing == nil else { return }
        self.pairing = pairing

        // What the phone copied goes onto this Mac's pasteboard directly —
        // "copy there, paste here" is the point, not a list to click through.
        pairing.$incomingClip
            .compactMap { $0 }
            .sink { [weak self] text in self?.write(text) }
            .store(in: &cancellables)

        // The phone cannot volunteer its clipboard from the background — Android
        // forbids the read outright — so the Mac asks, at the one moment the
        // answer is about to matter: you have just turned to this machine to
        // paste. See ClipboardReader on the phone side.
        NotificationCenter.default
            .publisher(for: NSApplication.didBecomeActiveNotification)
            .sink { [weak pairing] _ in pairing?.requestClipboard() }
            .store(in: &cancellables)

        let timer = Timer.scheduledTimer(withTimeInterval: 0.7, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        // The main run loop drops timers while a menu is open or a window is
        // being dragged; .common keeps the clipboard live through both.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// The convention password managers use to mark a copy as not for history
    /// or sync (nspasteboard.org). 1Password, Keychain Access and friends set
    /// it, and honouring it keeps passwords off the phone.
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    /// Set by apps that want a copy left out of automated tooling entirely.
    private static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGenerated =
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        // Check before reading the string at all: a concealed copy should not
        // be pulled off the pasteboard, let alone put on the wire.
        let types = pasteboard.types ?? []
        guard !types.contains(Self.concealed),
              !types.contains(Self.transient),
              !types.contains(Self.autoGenerated) else { return }
        guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }
        guard text != lastText else { return }
        lastText = text
        pairing?.sendClipboard(text)
    }

    /// Puts the phone's clipboard on this Mac, without treating it as a new copy.
    private func write(_ text: String) {
        guard text != lastText else { return }
        lastText = text
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }
}
